language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - gfortran

after_success:
  - curl https://markov-chain.github.io/travis/documentation.sh | bash

env:
  global:
    - CRATE_NAME=threed_ice_sys
    - secure: R3Ef1d9Sv3sh5yN/dz+XvjmlNmCQgoP4QOI15U0ViLbKMHMTiTP1sjAUnrKmTFpv+6u1gZdSkg5tFRwPXqlo469Hxqs7zQ8ntDykKIcyi85cfU0jhtU9SaObG30w7eNZPUqyhXUTDxUb8TiH50bdGqFUhsqpS2Y5E1LFElHGTY7QwG57DWABmq8FsNsQcdomX5ntORkTHUB3vKV4UC0U7b482xD5SkAtpPP7SdpaBx2BMTZhzTlua0L5G+H94kFaF46F0VlNELN93DNn21jnpVmzMMChwm6iH+K4BzM+v/GYScmQVcJOF8F+3Golx/zmou7NcSLGire4Ub+qh9crtDMIOIoeZLzfwEW6ds3Bx9Y0xv8zdRju226j0cxrGD/prSMMnezaaVK8EXwHunAqXcjaaDTyUKrEQ9J+mhdjWstlyaBal6ox8t1ycGimy97JuzPHPeNaRhXi4EJNyfmsBORmzi5MOks1eeilkUKAaI2QgACp4hBlAlbbZTVBUuJk+lfdxRZt5Iifc3xCDkpkZeMI5rd3h1SHGtkatxv+N3tfa11zl1tG4O8MJdgXnxZq2syybLDJNL4BS+FIBq3ajjqAw1W4tTGKHsdi3gxAWmGDyv2diB/00Cq2jWIP0AIdVZ/lxaWlF4gtErDDJ4SHk63d24ZB3Ez3bi969ssdajo=

notifications:
  email: false
