language: rust
sudo: required

before_install:
  - sudo apt-get install gfortran

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | CRATE_NAME=threed_ice_sys bash

script:
  - cargo build --verbose
  - cargo test --verbose -- --nocapture

env:
  global:
    secure: gwaRcq70MAidzr+H+loGm+/02AWmspKq9tz7M+Dytoz8JQhGsTyTOFy1Cqp4EK08Bu3YSnuNTqXtKEf1hUg0s3/WTfMsd1vFuO+6nrEdBXdFaj1uf4952PFBJCUQof2uD5L5eur0Sxi2uLuhJ++6LVImN1mQbnZWVDmyW2EdMc3YUWHb61NOO4tpvQ9g38Ezmk6GAOxQtJATdoy+gLW7iRHwCjQU2YwMVopq7COJ31lPtQBRGjkmc/fXDdGL4GjnKpF6gu28RelPgTrOQchNsAsQbboJK9c8wFEBoIfwc8fgWBxZBH+Zmubb1uZgG8Hm5z09Y70XWlw6P10bASHFPxoBe6CPbgTIPWQUNCBZa4LWjCJ26eJWzkwbdXNYC95V3XwIx62aIlx8Ab/7xGnpCmR3Y1UQZKHhZpHvpwkxTT0bQkD6XvLlRKvZ9yzHOsYt7lhqtASqkzpof/lCEb0vaT5auWgRw5GPnUn/Nq0xw1jJLMfzyhoHovvEhDCSH9ne7l2UedV586dIcgsArBiY91zhVIQu/GZH8u0xby1KC+GTKL4STgsW+S9dq8Zp8SMWO4/K3utQagwG4UDiFC2dBPQhg+NWVhXsyWSqCqNxMzIYhtOoNZtShi2ZtRVINtr1tcZGgcicG+iZEc4tt54ZUSFwLmOX/o0FgZIWjRW/HaY=

notifications:
  email: false
